= chunkify
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Black: https://black.readthedocs.io/en/stable/[Black]
:Fedora: https://getfedora.com/[Fedora]
:Git: https://git-scm.com/[Git]
:itertools: https://docs.python.org/3/library/itertools.html[itertools]
:mypy: http://www.mypy-lang.org/[mypy]
:Poetry: https://python-poetry.org[Poetry]
:pre-commit: https://pre-commit.com/[pre-commit]
:Pylint: http://pylint.pycqa.org/en/latest/[Pylint]
:pytest: https://docs.pytest.org/en/stable/[pytest]
:Python: https://www.python.org/[Python]

// todo Migrate CI to Codeberg.
// image:https://img.shields.io/github/workflow/status/jwillikers/chunkify/CI[GitHub Workflow Status]

An implementation of the grouping function documented in the {itertools} {Python} module.
The function is dubbed _chunkify_ here.

== Getting Started

The steps below will create an environment for building the project.
These steps assume you are on {Fedora} and familiar with the Linux command-line and {Git}.

. Clone the project's repository from GitHub.
+
[,sh]
----
git clone https://codeberg.org/jwillikers/chunkify.git
----

. Change into the project's directory.
+
[,sh]
----
cd chunkify
----

. Install {Poetry}.
+
[,sh]
----
sudo dnf -y install poetry
----

. Install the dependencies with Poetry.
+
[,sh]
----
poetry install
----

. Install the pre-commit hooks for the project.
+
[,sh]
----
poetry run pre-commit install
----

=== Format

Use Black to format the Python code.

[,sh]
----
poetry run black .
----

=== Lint

Check the project for common programming errors with {Pylint}.

[,sh]
----
poetry run pylint -j 0 *.py
----

=== Check Static Typing

Check static typing with {mypy}.

[,sh]
----
poetry run mypy *.py
----

=== Test

Test cases are available for _chunkify_.
Execute them with {pytest}.
From the root directory of the project, run `pytest`.

[,sh]
----
poetry run pytest
----

=== Package

Build with Poetry.

[,sh]
----
poetry build
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* https://asciidoctor.org/[Asciidoctor]
* {Black}
* {Git}
* {mypy}
* {Poetry}
* {pre-commit}
* {Pylint}
* {pytest}
* {Python}
* https://rouge.jneen.net/[Rouge]
* https://www.ruby-lang.org/en/[Ruby]

== Code of Conduct

Refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], a copy of which is available link:LICENSE.adoc[here].

© 2020-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
