---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install Python dependencies
        run: poetry install
      - name: Check formatting with Black
        run: poetry run black --check .
      - name: Lint with Pylint
        run: poetry run pylint -j 0 chunkify
      - name: Check static typing with mypy
        run: poetry run mypy chunkify
      - name: Test with pytest
        run: poetry run pytest
