---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Pipenv
        run: pip install pipenv
      - name: Configure Pipenv
        run: pipenv install --dev
      - name: Check formatting with Black
        run: pipenv run black --check .
      - name: Lint with Pylint
        run: pipenv run pylint -j 0 *.py
      - name: Check static typing with mypy
        run: pipenv run mypy *.py
      - name: Test with pytest
        run: pipenv run pytest
