---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Check formatting with Black
        run: black --check .
      - name: Lint with Pylint
        run: pylint -j 0 chunkify
      - name: Check static typing with mypy
        run: mypy chunkify
      - name: Test with pytest
        run: pytest
